namespace: frantchenco
name: helm_wrapper
version: 1.0.0
readme: README.md
authors:
  - your name <example@domain.com>
description: Helm wrapper to install helm package with retry
license_file: 'LICENSE'
tags: []
# dependencies:
#   "kubernetes.core":"*"
repository: https://github.com/Frantche/ansible_collection_helm_wrapper
documentation: http://docs.example.com
homepage: http://example.com
issues: https://github.com/Frantche/ansible_collection_helm_wrapper/issues
build_ignore: []
